# Generated by Django 5.2.7 on 2025-10-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_warga_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
    ]
